namespace PixelPlanetBot
{
    enum PixelColor : byte
    {
        NothingOcean,
        NothingLand,
        White,
        LightGray,
        MediumGray,
        DarkGray,
        Black,
        BodyPink,
        Pink,
        LightRed,
        Red,
        Peach,
        Orange,
        LightBrown,
        Wheat,
        Yellow,
        LightGreen,
        Green,
        DarkGreen,
        LightestBlue,
        Cyan,
        LightBlue,
        Blue,
        DarkBlue,
        Orchid,
        Violet,
        None
    }
}
