namespace PixelPlanetUtils
{
    public enum PixelColor : byte
    {
        UnsetOcean,
        UnsetLand,
        White,
        LightGray,
        Silver,
        DarkGray,
        DarkerGray,
        Black,
        Skin,
        LightPink,
        Pink,
        Peach,
        Red,
        DarkRed,
        LightBrown,
        Orange,
        Brown,
        DarkBrown,
        Sand,
        Khaki,
        Yellow,
        LightGreen,
        Green,
        Olive,
        DarkGreen,
        SkyBlue,
        LightBlue,
        DarkBlue,
        Blue,
        DarkerBlue,
        LightViolette,
        Violette,
        None
    }
}
