namespace PixelPlanetUtils
{
    public enum PixelColor : byte
    {
        UnsetOcean,
        UnsetLand,
        White,
        LightGray,
        DarkGray,
        DarkerGray,
        Black,
        LightPink,
        Pink,
        Peach,
        Red,
        LightBrown,
        Orange,
        Brown,
        Sand,
        Yellow,
        LightGreen,
        Green,
        DarkGreen,
        SkyBlue,
        LightBlue,
        DarkBlue,
        Blue,
        DarkerBlue,
        LightViolette,
        Violette,
        None
    }
}
